name: Tag on Merge to Master

on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get the latest tag
      id: get-latest-tag
      run: |
        latest_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")
        echo "tag=$latest_tag" >> $GITHUB_ENV

    - name: Create new tag version
      id: new-tag
      run: |
        latest_tag=$tag
        if [[ $latest_tag == v* ]]; then
          version=${latest_tag:1}
        else
          version=$latest_tag
        fi
        IFS='.' read -ra version_parts <<< "$version"
        major=${version_parts[0]}
        minor=${version_parts[1]}
        patch=${version_parts[2]}
        patch=$((patch+1))
        new_tag="v$major.$minor.$patch"
        echo "new_tag=$new_tag" >> $GITHUB_ENV

    - name: Create a new tag in the repository
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git tag $new_tag
        git push origin $new_tag
